/*
 jquery.layout 1.3.0 - Release Candidate 29.8
 $Date: 2010-09-27 08:00:00 (Mon, 27 Sep 2010) $
 $Rev: 30298 $

 Copyright (c) 2010 
 Fabrizio Balliano (http://www.fabrizioballiano.net)
 Kevin Dalman (http://allpro.net)

 Dual licensed under the GPL (http://www.gnu.org/licenses/gpl.html)
 and MIT (http://www.opensource.org/licenses/mit-license.php) licenses.

 Docs: http://layout.jquery-dev.net/documentation.html
 Tips: http://layout.jquery-dev.net/tips.html
 Help: http://groups.google.com/group/jquery-ui-layout
*/
(function(i){var ja=i.browser;i.layout={browser:{mozilla:ja.mozilla,webkit:ja.webkit||ja.safari||false,msie:ja.msie,isIE6:ja.msie&&ja.version==6,boxModel:false},scrollbarWidth:function(){return window.scrollbarWidth||i.layout.getScrollbarSize("width")},scrollbarHeight:function(){return window.scrollbarHeight||i.layout.getScrollbarSize("height")},getScrollbarSize:function(p){var v=i('<div style="position: absolute; top: -10000px; left: -10000px; width: 100px; height: 100px; overflow: scroll;"></div>').appendTo("body"),
w={width:v.width()-v[0].clientWidth,height:v.height()-v[0].clientHeight};v.remove();window.scrollbarWidth=w.width;window.scrollbarHeight=w.height;return p.match(/^(width|height)$/i)?w[p]:w},showInvisibly:function(p,v){if(!p)return{};p.jquery||(p=i(p));var w={display:p.css("display"),visibility:p.css("visibility")};if(v||w.display=="none"){p.css({display:"block",visibility:"hidden"});return w}else return{}},getElemDims:function(p){var v={},w=v.css={},y={},P,X,Y=p.offset();v.offsetLeft=Y.left;v.offsetTop=
Y.top;i.each("Left,Right,Top,Bottom".split(","),function(H,G){P=w["border"+G]=i.layout.borderWidth(p,G);X=w["padding"+G]=i.layout.cssNum(p,"padding"+G);y[G]=P+X;v["inset"+G]=X});v.offsetWidth=p.innerWidth();v.offsetHeight=p.innerHeight();v.outerWidth=p.outerWidth();v.outerHeight=p.outerHeight();v.innerWidth=v.outerWidth-y.Left-y.Right;v.innerHeight=v.outerHeight-y.Top-y.Bottom;w.width=p.width();w.height=p.height();return v},getElemCSS:function(p,v){var w={},y=p[0].style,P=v.split(","),X="Top,Bottom,Left,Right".split(","),
Y="Color,Style,Width".split(","),H,G,ka,Z,$,ga;for(Z=0;Z<P.length;Z++){H=P[Z];if(H.match(/(border|padding|margin)$/))for($=0;$<4;$++){G=X[$];if(H=="border")for(ga=0;ga<3;ga++){ka=Y[ga];w[H+G+ka]=y[H+G+ka]}else w[H+G]=y[H+G]}else w[H]=y[H]}return w},cssWidth:function(p,v){var w=i.layout.borderWidth,y=i.layout.cssNum;if(v<=0)return 0;if(!i.layout.browser.boxModel)return v;w=v-w(p,"Left")-w(p,"Right")-y(p,"paddingLeft")-y(p,"paddingRight");return w>0?w:0},cssHeight:function(p,v){var w=i.layout.borderWidth,
y=i.layout.cssNum;if(v<=0)return 0;if(!i.layout.browser.boxModel)return v;w=v-w(p,"Top")-w(p,"Bottom")-y(p,"paddingTop")-y(p,"paddingBottom");return w>0?w:0},cssNum:function(p,v){p.jquery||(p=i(p));var w=i.layout.showInvisibly(p),y=parseInt(i.curCSS(p[0],v,true),10)||0;p.css(w);return y},borderWidth:function(p,v){if(p.jquery)p=p[0];var w="border"+v.substr(0,1).toUpperCase()+v.substr(1);return i.curCSS(p,w+"Style",true)=="none"?0:parseInt(i.curCSS(p,w+"Width",true),10)||0}};i.fn.layout=function(p){function v(a){if(!a)return true;
var b=a.keyCode;if(b<33)return true;var c={38:"north",40:"south",37:"west",39:"east"},e=a.shiftKey,d=a.ctrlKey,h,g,f,j;if(d&&b>=37&&b<=40&&n[c[b]].enableCursorHotkey)j=c[b];else if(d||e)i.each(k.borderPanes.split(","),function(o,m){h=n[m];g=h.customHotkey;f=h.customHotkeyModifier;if(e&&f=="SHIFT"||d&&f=="CTRL"||d&&e)if(g&&b==(isNaN(g)||g<=9?g.toUpperCase().charCodeAt(0):g)){j=m;return false}});if(!j||!q[j]||!n[j].closable||l[j].isHidden)return true;la(j);a.stopPropagation();return a.returnValue=false}
function w(a){if(this&&this.tagName)a=this;var b;if(M(a))b=q[a];else if(i(a).data("layoutRole"))b=i(a);else i(a).parents().each(function(){if(i(this).data("layoutRole")){b=i(this);return false}});if(b&&b.length){var c=b.data("layoutEdge");a=l[c];a.cssSaved&&y(c);if(a.isSliding||a.isResizing||a.isClosed)a.cssSaved=false;else{var e={zIndex:k.zIndex.pane_normal+2},d={},h=b.css("overflow"),g=b.css("overflowX"),f=b.css("overflowY");if(h!="visible"){d.overflow=h;e.overflow="visible"}if(g&&!g.match(/visible|auto/)){d.overflowX=
g;e.overflowX="visible"}if(f&&!f.match(/visible|auto/)){d.overflowY=g;e.overflowY="visible"}a.cssSaved=d;b.css(e);i.each(k.allPanes.split(","),function(j,o){o!=c&&y(o)})}}}function y(a){if(this&&this.tagName)a=this;var b;if(M(a))b=q[a];else if(i(a).data("layoutRole"))b=i(a);else i(a).parents().each(function(){if(i(this).data("layoutRole")){b=i(this);return false}});if(b&&b.length){a=b.data("layoutEdge");a=l[a];var c=a.cssSaved||{};!a.isSliding&&!a.isResizing&&b.css("zIndex",k.zIndex.pane_normal);
b.css(c);a.cssSaved=false}}function P(a,b,c){var e=i(a);if(e.length)if(k.borderPanes.indexOf(b)==-1)alert(C.errButton+C.Pane.toLowerCase()+": "+b);else{a=n[b].buttonClass+"-"+c;e.addClass(a+" "+a+"-"+b).data("layoutName",n.name);return e}else alert(C.errButton+C.selector+": "+a);return null}function X(a,b,c){switch(b.toLowerCase()){case "toggle":Y(a,c);break;case "open":H(a,c);break;case "close":G(a,c);break;case "pin":ka(a,c);break;case "toggle-slide":Y(a,c,true);break;case "open-slide":H(a,c,true)}}
function Y(a,b,c){(a=P(a,b,"toggle"))&&a.click(function(e){la(b,!!c);e.stopPropagation()})}function H(a,b,c){(a=P(a,b,"open"))&&a.attr("title",C.Open).click(function(e){aa(b,!!c);e.stopPropagation()})}function G(a,b){var c=P(a,b,"close");c&&c.attr("title",C.Close).click(function(e){Q(b);e.stopPropagation()})}function ka(a,b){var c=P(a,b,"pin");if(c){var e=l[b];c.click(function(d){$(i(this),b,e.isSliding||e.isClosed);e.isSliding||e.isClosed?aa(b):Q(b);d.stopPropagation()});$(c,b,!e.isClosed&&!e.isSliding);
k[b].pins.push(a)}}function Z(a,b){i.each(k[a].pins,function(c,e){$(i(e),a,b)})}function $(a,b,c){var e=a.attr("pin");if(!(e&&c==(e=="down"))){e=n[b].buttonClass+"-pin";var d=e+"-"+b;b=e+"-up "+d+"-up";e=e+"-down "+d+"-down";a.attr("pin",c?"down":"up").attr("title",c?C.Unpin:C.Pin).removeClass(c?b:e).addClass(c?e:b)}}function ga(a){a=i.extend({},n.cookie,a||{}).name||n.name||"Layout";var b=document.cookie;b=b?b.split(";"):[];for(var c,e=0,d=b.length;e<d;e++){c=i.trim(b[e]).split("=");if(c[0]==a)return Ka(decodeURIComponent(c[1]))}return""}
function Aa(a,b){var c=i.extend({},n.cookie,b||{}),e=c.name||n.name||"Layout",d="",h="",g=false;if(c.expires.toUTCString)h=c.expires;else if(typeof c.expires=="number"){h=new Date;if(c.expires>0)h.setDate(h.getDate()+c.expires);else{h.setYear(1970);g=true}}if(h)d+=";expires="+h.toUTCString();if(c.path)d+=";path="+c.path;if(c.domain)d+=";domain="+c.domain;if(c.secure)d+=";secure";if(g){l.cookie={};document.cookie=e+"="+d}else{l.cookie=Ba(a||c.keys);document.cookie=e+"="+encodeURIComponent(La(l.cookie))+
d}return i.extend({},l.cookie)}function Ma(a){if(a=ga(a)){l.cookie=i.extend({},a);Na(a)}return a}function Na(a){i.extend(true,n,a)}function Ba(a){var b={},c={isClosed:"initClosed",isHidden:"initHidden"},e,d,h;if(!a)a=n.cookie.keys;if(i.isArray(a))a=a.join(",");a=a.replace(/__/g,".").split(",");for(var g=0,f=a.length;g<f;g++){e=a[g].split(".");d=e[0];e=e[1];if(!(k.allPanes.indexOf(d)<0)){h=l[d][e];if(h!=undefined){if(e=="isClosed"&&l[d].isSliding)h=true;(b[d]||(b[d]={}))[c[e]?c[e]:e]=h}}}return b}
function La(a){function b(c){var e=[],d=0,h,g,f;for(h in c){g=c[h];f=typeof g;if(f=="string")g='"'+g+'"';else if(f=="object")g=b(g);e[d++]='"'+h+'":'+g}return"{"+e.join(",")+"}"}return b(a)}function Ka(a){try{return window.eval("("+a+")")||{}}catch(b){return{}}}var C={Pane:"Pane",Open:"Open",Close:"Close",Resize:"Resize",Slide:"Slide Open",Pin:"Pin",Unpin:"Un-Pin",selector:"selector",msgNoRoom:"Not enough room to show this pane.",errContainerMissing:"UI Layout Initialization Error\n\nThe specified layout-container does not exist.",
errCenterPaneMissing:"UI Layout Initialization Error\n\nThe center-pane element does not exist.\n\nThe center-pane is a required element.",errContainerHeight:"UI Layout Initialization Warning\n\nThe layout-container \"CONTAINER\" has no height.\n\nTherefore the layout is 0-height and hence 'invisible'!",errButton:"Error Adding Button \n\nInvalid "},n={name:"",scrollToBookmarkOnLoad:true,resizeWithWindow:true,resizeWithWindowDelay:200,resizeWithWindowMaxDelay:0,onresizeall_start:null,onresizeall_end:null,
onload:null,onunload:null,autoBindCustomButtons:false,zIndex:null,defaults:{applyDemoStyles:false,closable:true,resizable:true,slidable:true,initClosed:false,initHidden:false,contentSelector:".ui-layout-content",contentIgnoreSelector:".ui-layout-ignore",findNestedContent:false,paneClass:"ui-layout-pane",resizerClass:"ui-layout-resizer",togglerClass:"ui-layout-toggler",buttonClass:"ui-layout-button",minSize:0,maxSize:0,spacing_open:6,spacing_closed:6,togglerLength_open:50,togglerLength_closed:50,togglerAlign_open:"center",
togglerAlign_closed:"center",togglerTip_open:C.Close,togglerTip_closed:C.Open,togglerContent_open:"",togglerContent_closed:"",resizerDblClickToggle:true,autoResize:true,autoReopen:true,resizerDragOpacity:1,maskIframesOnResize:true,resizeNestedLayout:true,resizeWhileDragging:false,resizeContentWhileDragging:false,noRoomToOpenTip:C.msgNoRoom,resizerTip:C.Resize,sliderTip:C.Slide,sliderCursor:"pointer",slideTrigger_open:"click",slideTrigger_close:"mouseleave",hideTogglerOnSlide:false,preventQuickSlideClose:!!(i.browser.webkit||
i.browser.safari),showOverflowOnHover:false,enableCursorHotkey:true,customHotkeyModifier:"SHIFT",fxName:"slide",fxSpeed:null,fxSettings:{},fxOpacityFix:true,triggerEventsOnLoad:false,triggerEventsWhileDragging:true,onshow_start:null,onshow_end:null,onhide_start:null,onhide_end:null,onopen_start:null,onopen_end:null,onclose_start:null,onclose_end:null,onresize_start:null,onresize_end:null,onsizecontent_start:null,onsizecontent_end:null,onswap_start:null,onswap_end:null,ondrag_start:null,ondrag_end:null},
north:{paneSelector:".ui-layout-north",size:"auto",resizerCursor:"n-resize",customHotkey:""},south:{paneSelector:".ui-layout-south",size:"auto",resizerCursor:"s-resize",customHotkey:""},east:{paneSelector:".ui-layout-east",size:200,resizerCursor:"e-resize",customHotkey:""},west:{paneSelector:".ui-layout-west",size:200,resizerCursor:"w-resize",customHotkey:""},center:{paneSelector:".ui-layout-center",minWidth:0,minHeight:0},useStateCookie:false,cookie:{name:"",autoSave:true,autoLoad:true,domain:"",
path:"",expires:"",secure:false,keys:"north.size,south.size,east.size,west.size,north.isClosed,south.isClosed,east.isClosed,west.isClosed,north.isHidden,south.isHidden,east.isHidden,west.isHidden"}},Ca={slide:{all:{duration:"fast"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},west:{direction:"left"}},drop:{all:{duration:"slow"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},west:{direction:"left"}},scale:{all:{duration:"fast"}}},l={id:"layout"+
(new Date).getTime(),initialized:false,container:{},north:{},south:{},east:{},west:{},center:{},cookie:{}},k={allPanes:"north,south,west,east,center",borderPanes:"north,south,west,east",altSide:{north:"south",south:"north",east:"west",west:"east"},hidden:{visibility:"hidden"},visible:{visibility:"visible"},zIndex:{pane_normal:1,resizer_normal:2,iframe_mask:2,pane_sliding:100,pane_animate:1E3,resizer_drag:1E4},resizers:{cssReq:{position:"absolute",padding:0,margin:0,fontSize:"1px",textAlign:"left",
overflow:"hidden"},cssDemo:{background:"#DDD",border:"none"}},togglers:{cssReq:{position:"absolute",display:"block",padding:0,margin:0,overflow:"hidden",textAlign:"center",fontSize:"1px",cursor:"pointer",zIndex:1},cssDemo:{background:"#AAA"}},content:{cssReq:{position:"relative"},cssDemo:{overflow:"auto",padding:"10px"},cssDemoPane:{overflow:"hidden",padding:0}},panes:{cssReq:{position:"absolute",margin:0},cssDemo:{padding:"10px",background:"#FFF",border:"1px solid #BBB",overflow:"auto"}},north:{side:"Top",
sizeType:"Height",dir:"horz",cssReq:{top:0,bottom:"auto",left:0,right:0,width:"auto"},pins:[]},south:{side:"Bottom",sizeType:"Height",dir:"horz",cssReq:{top:"auto",bottom:0,left:0,right:0,width:"auto"},pins:[]},east:{side:"Right",sizeType:"Width",dir:"vert",cssReq:{left:"auto",right:0,top:"auto",bottom:"auto",height:"auto"},pins:[]},west:{side:"Left",sizeType:"Width",dir:"vert",cssReq:{left:0,right:"auto",top:"auto",bottom:"auto",height:"auto"},pins:[]},center:{dir:"center",cssReq:{left:"auto",right:"auto",
top:"auto",bottom:"auto",height:"auto",width:"auto"}}},D={data:{},set:function(a,b,c){D.clear(a);D.data[a]=setTimeout(b,c)},clear:function(a){var b=D.data;if(b[a]){clearTimeout(b[a]);delete b[a]}}},M=function(a){try{return typeof a=="string"||typeof a=="object"&&a.constructor.toString().match(/string/i)!==null}catch(b){return false}},z=function(a,b){return Math.max(a,b)},$a=function(a){var b,c={cookie:{},defaults:{fxSettings:{}},north:{fxSettings:{}},south:{fxSettings:{}},east:{fxSettings:{}},west:{fxSettings:{}},
center:{fxSettings:{}}};a=a||{};if(a.effects||a.cookie||a.defaults||a.north||a.south||a.west||a.east||a.center)c=i.extend(true,c,a);else i.each(a,function(e,d){b=e.split("__");if(!b[1]||c[b[0]])c[b[1]?b[0]:"defaults"][b[1]?b[1]:b[0]]=d});return c},Oa=function(a,b,c){function e(h){var g=k[h];if(g.doCallback){d.push(h);h=g.callback.split(",")[1];h!=b&&!i.inArray(h,d)>=0&&e(h)}else{g.doCallback=true;g.callback=a+","+b+","+(c?1:0)}}var d=[];i.each(k.borderPanes.split(","),function(h,g){if(k[g].isMoving){e(g);
return false}})},Pa=function(a){a=k[a];k.isLayoutBusy=false;delete a.isMoving;if(a.doCallback&&a.callback){a.doCallback=false;var b=a.callback.split(","),c=b[2]>0?true:false;if(b[0]=="open")aa(b[1],c);else b[0]=="close"&&Q(b[1],c);if(!a.doCallback)a.callback=null}},x=function(a,b){if(b){var c;try{if(typeof b=="function")c=b;else if(M(b))if(b.match(/,/)){var e=b.split(",");c=eval(e[0]);if(typeof c=="function"&&e.length>1)return c(e[1])}else c=eval(b);else return;if(typeof c=="function")return a&&q[a]?
c(a,q[a],i.extend({},l[a]),n[a],n.name):c(Qa,i.extend({},l),n,n.name)}catch(d){}}},Ra=function(a,b){if(!a)return{};a.jquery||(a=i(a));var c={display:a.css("display"),visibility:a.css("visibility")};if(b||c.display=="none"){a.css({display:"block",visibility:"hidden"});return c}else return{}},Sa=function(a){if(!l.browser.mozilla){var b=q[a];l[a].tagName=="IFRAME"?b.css(k.hidden).css(k.visible):b.find("IFRAME").css(k.hidden).css(k.visible)}},ha=function(a,b){a.jquery||(a=i(a));var c=Ra(a),e=parseInt(i.curCSS(a[0],
b,true),10)||0;a.css(c);return e},oa=function(a,b){if(a.jquery)a=a[0];var c="border"+b.substr(0,1).toUpperCase()+b.substr(1);return i.curCSS(a,c+"Style",true)=="none"?0:parseInt(i.curCSS(a,c+"Width",true),10)||0},N=function(a,b){var c=M(a),e=c?q[a]:i(a);if(isNaN(b))b=c?T(a):e.outerWidth();if(b<=0)return 0;if(!l.browser.boxModel)return b;c=b-oa(e,"Left")-oa(e,"Right")-ha(e,"paddingLeft")-ha(e,"paddingRight");return c>0?c:0},O=function(a,b){var c=M(a),e=c?q[a]:i(a);if(isNaN(b))b=c?T(a):e.outerHeight();
if(b<=0)return 0;if(!l.browser.boxModel)return b;c=b-oa(e,"Top")-oa(e,"Bottom")-ha(e,"paddingTop")-ha(e,"paddingBottom");return c>0?c:0},va=function(a){var b=k[a].dir;a={minWidth:1001-N(a,1E3),minHeight:1001-O(a,1E3)};if(b=="horz")a.minSize=a.minHeight;if(b=="vert")a.minSize=a.minWidth;return a},ab=function(a,b,c){var e=a;if(M(a))e=q[a];else a.jquery||(e=i(a));a=O(e,b);e.css({height:a,visibility:"visible"});if(a>0&&e.innerWidth()>0){if(c&&e.data("autoHidden")){e.show().data("autoHidden",false);l.browser.mozilla||
e.css(k.hidden).css(k.visible)}}else c&&!e.data("autoHidden")&&e.hide().data("autoHidden",true)},ba=function(a,b,c){if(!c)c=k[a].dir;if(M(b)&&b.match(/%/))b=parseInt(b,10)/100;if(b===0)return 0;else if(b>=1)return parseInt(b,10);else if(b>0){a=n;var e;if(c=="horz")e=r.innerHeight-(q.north?a.north.spacing_open:0)-(q.south?a.south.spacing_open:0);else if(c=="vert")e=r.innerWidth-(q.west?a.west.spacing_open:0)-(q.east?a.east.spacing_open:0);return Math.floor(e*b)}else if(a=="center")return 0;else{e=
q[a];c=c=="horz"?"height":"width";a=Ra(e);var d=e.css(c);e.css(c,"auto");b=c=="height"?e.outerHeight():e.outerWidth();e.css(c,d).css(a);return b}},T=function(a,b){var c=q[a],e=n[a],d=l[a],h=b?e.spacing_open:0;e=b?e.spacing_closed:0;return!c||d.isHidden?0:d.isClosed||d.isSliding&&b?e:k[a].dir=="horz"?c.outerHeight()+h:c.outerWidth()+h},U=function(a,b){var c=n[a],e=l[a],d=k[a],h=d.dir;d.side.toLowerCase();d.sizeType.toLowerCase();d=b!=undefined?b:e.isSliding;var g=c.spacing_open,f=k.altSide[a],j=l[f],
o=q[f],m=!o||j.isVisible===false||j.isSliding?0:h=="horz"?o.outerHeight():o.outerWidth();f=(!o||j.isHidden?0:n[f][j.isClosed!==false?"spacing_closed":"spacing_open"])||0;j=h=="horz"?r.innerHeight:r.innerWidth;o=va("center");o=h=="horz"?z(n.center.minHeight,o.minHeight):z(n.center.minWidth,o.minWidth);d=j-g-(d?0:ba("center",o,h)+m+f);h=e.minSize=z(ba(a,c.minSize),va(a).minSize);g=c.maxSize?ba(a,c.maxSize):1E5;d=e.maxSize=Math.min(g,d);e=e.resizerPosition={};g=r.insetTop;m=r.insetLeft;f=r.innerWidth;
j=r.innerHeight;c=c.spacing_open;switch(a){case "north":e.min=g+h;e.max=g+d;break;case "west":e.min=m+h;e.max=m+d;break;case "south":e.min=g+j-d-c;e.max=g+j-h-c;break;case "east":e.min=m+f-d-c;e.max=m+f-h-c}},ia=function(a){var b={},c=b.css={},e={},d,h,g=a.offset();b.offsetLeft=g.left;b.offsetTop=g.top;i.each("Left,Right,Top,Bottom".split(","),function(f,j){d=c["border"+j]=oa(a,j);h=c["padding"+j]=ha(a,"padding"+j);e[j]=d+h;b["inset"+j]=h});b.offsetWidth=a.innerWidth();b.offsetHeight=a.innerHeight();
b.outerWidth=a.outerWidth();b.outerHeight=a.outerHeight();b.innerWidth=b.outerWidth-e.Left-e.Right;b.innerHeight=b.outerHeight-e.Top-e.Bottom;c.width=a.width();c.height=a.height();return b},Da=function(a,b){var c={},e=a[0].style,d=b.split(","),h="Top,Bottom,Left,Right".split(","),g="Color,Style,Width".split(","),f,j,o,m,t,s;for(m=0;m<d.length;m++){f=d[m];if(f.match(/(border|padding|margin)$/))for(t=0;t<4;t++){j=h[t];if(f=="border")for(s=0;s<3;s++){o=g[s];c[f+j+o]=e[f+j+o]}else c[f+j]=e[f+j]}else c[f]=
e[f]}return c},Ea=function(a,b){var c=i(a),e=c.data("layoutRole"),d=c.data("layoutEdge"),h=n[d][e+"Class"];d="-"+d;var g=c.hasClass(h+"-closed")?"-closed":"-open",f=g=="-closed"?"-open":"-closed";g=h+"-hover "+(h+d+"-hover ")+(h+g+"-hover ")+(h+d+g+"-hover ");if(b)g+=h+f+"-hover "+(h+d+f+"-hover ");if(e=="resizer"&&c.hasClass(h+"-sliding"))g+=h+"-sliding-hover "+(h+d+"-sliding-hover ");return i.trim(g)},pa=function(a,b){var c=b||this;i(c).addClass(Ea(c))},V=function(a,b){var c=b||this;i(c).removeClass(Ea(c,
true))},bb=function(a){i("body").disableSelection();pa(a,this)},Ta=function(a,b){var c=b||this,e=i(c).data("layoutEdge"),d=e+"ResizerLeave";D.clear(d);if(b)l[e].isResizing||i("body").enableSelection();else{V(a,this);D.set(d,function(){Ta(a,c)},200)}},cb=function(){var a=Number(n.resizeWithWindowDelay)||100;if(a>0){D.clear("winResize");D.set("winResize",function(){D.clear("winResize");D.clear("winResizeRepeater");wa()},a);D.data.winResizeRepeater||Ua()}},Ua=function(){var a=Number(n.resizeWithWindowMaxDelay);
a>0&&D.set("winResizeRepeater",function(){Ua();wa()},a)},Va=function(){var a=n;l.cookie=Ba();a.useStateCookie&&a.cookie.autoSave&&Aa();x(null,a.onunload)},db=function(){i.each(k.borderPanes.split(","),function(a,b){var c=n[b];if(c.enableCursorHotkey||c.customHotkey){i(document).bind("keydown."+E,v);return false}})},eb=function(){function a(g){for(var f in b)if(g[f]!=undefined){g[b[f]]=g[f];delete g[f]}}p=$a(p);var b={applyDefaultStyles:"applyDemoStyles"};a(p.defaults);i.each(k.allPanes.split(","),
function(g,f){a(p[f])});if(p.effects){i.extend(Ca,p.effects);delete p.effects}i.extend(n.cookie,p.cookie);i.each("name,zIndex,scrollToBookmarkOnLoad,resizeWithWindow,resizeWithWindowDelay,resizeWithWindowMaxDelay,onresizeall,onresizeall_start,onresizeall_end,onload,onunload,autoBindCustomButtons,useStateCookie".split(","),function(g,f){if(p[f]!==undefined)n[f]=p[f];else if(p.defaults[f]!==undefined){n[f]=p.defaults[f];delete p.defaults[f]}});i.each("paneSelector,resizerCursor,customHotkey".split(","),
function(g,f){delete p.defaults[f]});i.extend(true,n.defaults,p.defaults);k.center=i.extend(true,{},k.panes,k.center);var c=n.zIndex;if(c===0||c>0){k.zIndex.pane_normal=c;k.zIndex.resizer_normal=c+1;k.zIndex.iframe_mask=c+1}i.extend(n.center,p.center);var e=i.extend(true,{},n.defaults,p.defaults,n.center);c="paneClass,contentSelector,applyDemoStyles,triggerEventsOnLoad,showOverflowOnHover,onresize,onresize_start,onresize_end,resizeNestedLayout,resizeContentWhileDragging,onsizecontent,onsizecontent_start,onsizecontent_end".split(",");
i.each(c,function(g,f){n.center[f]=e[f]});var d,h=n.defaults;i.each(k.borderPanes.split(","),function(g,f){k[f]=i.extend(true,{},k.panes,k[f]);d=n[f]=i.extend(true,{},n.defaults,n[f],p.defaults,p[f]);if(!d.paneClass)d.paneClass="ui-layout-pane";if(!d.resizerClass)d.resizerClass="ui-layout-resizer";if(!d.togglerClass)d.togglerClass="ui-layout-toggler";i.each(["_open","_close",""],function(j,o){var m="fxName"+o,t="fxSpeed"+o,s="fxSettings"+o;d[m]=p[f][m]||p[f].fxName||p.defaults[m]||p.defaults.fxName||
d[m]||d.fxName||h[m]||h.fxName||"none";var u=d[m];if(u=="none"||!i.effects||!i.effects[u]||!Ca[u]&&!d[s]&&!d.fxSettings)u=d[m]="none";u=Ca[u]||{};m=u.all||{};u=u[f]||{};d[s]=i.extend({},m,u,h.fxSettings||{},h[s]||{},d.fxSettings,d[s],p.defaults.fxSettings,p.defaults[s]||{},p[f].fxSettings,p[f][s]||{});d[t]=p[f][t]||p[f].fxSpeed||p.defaults[t]||p.defaults.fxSpeed||d[t]||d[s].duration||d.fxSpeed||d.fxSettings.duration||h.fxSpeed||h.fxSettings.duration||u.duration||m.duration||"normal"})})},Wa=function(a){a=
n[a].paneSelector;if(a.substr(0,1)==="#")return B.find(a).eq(0);else{var b=B.children(a).eq(0);return b.length?b:B.children("form:first").children(a).eq(0)}},fb=function(){i.each(k.allPanes.split(","),function(a,b){var c=n[b],e=l[b],d=k[b],h=d.dir,g=b=="center",f={},j,o,m;ca[b]=false;j=q[b]=Wa(b);if(!j.length){q[b]=false;return true}j.data("layoutCSS")||j.data("layoutCSS",Da(j,"position,top,left,bottom,right,width,height,overflow,zIndex,display,backgroundColor,padding,margin,border"));j.data("layoutName",
n.name).data("layoutRole","pane").data("layoutEdge",b).css(d.cssReq).css("zIndex",k.zIndex.pane_normal).css(c.applyDemoStyles?d.cssDemo:{}).addClass(c.paneClass+" "+c.paneClass+"-"+b).bind("mouseenter."+E,pa).bind("mouseleave."+E,V);Xa(b,false);if(!g){o=e.size=ba(b,c.size);d=ba(b,c.minSize)||1;m=ba(b,c.maxSize)||1E5;if(o>0)o=z(Math.min(o,m),d)}e.tagName=j.attr("tagName");e.edge=b;e.noRoom=false;e.isVisible=true;if(!g){e.isClosed=false;e.isSliding=false;e.isResizing=false;e.isHidden=false}switch(b){case "north":f.top=
r.insetTop;f.left=r.insetLeft;f.right=r.insetRight;break;case "south":f.bottom=r.insetBottom;f.left=r.insetLeft;f.right=r.insetRight;break;case "west":f.left=r.insetLeft;break;case "east":f.right=r.insetRight}if(h=="horz")f.height=z(1,O(b,o));else if(h=="vert")f.width=z(1,N(b,o));j.css(f);h!="horz"&&da(b,true);j.css({visibility:"visible",display:"block"});if(c.initClosed&&c.closable)Q(b,true,true);else if(c.initHidden||c.initClosed)Fa(b);c.showOverflowOnHover&&j.hover(w,y)});Ya();i.each(k.borderPanes.split(","),
function(a,b){if(q[b]&&l[b].isVisible){U(b);ea(b)}});da("center");i.each(k.allPanes.split(","),function(a,b){var c=n[b];if(q[b]&&c.triggerEventsOnLoad&&l[b].isVisible)x(b,c.onresize_end||c.onresize)});B.innerHeight()<2&&alert(C.errContainerHeight.replace(/CONTAINER/,r.ref))},Ya=function(a){if(!a||a=="all")a=k.borderPanes;i.each(a.split(","),function(b,c){var e=q[c];A[c]=false;I[c]=false;if(e){e=n[c];var d=l[c],h=e.resizerClass,g=e.togglerClass;k[c].side.toLowerCase();var f="-"+c,j=A[c]=i("<div></div>"),
o=e.closable?I[c]=i("<div></div>"):false;!d.isVisible&&e.slidable&&j.attr("title",e.sliderTip).css("cursor",e.sliderCursor);j.attr("id",e.paneSelector.substr(0,1)=="#"?e.paneSelector.substr(1)+"-resizer":"").data("layoutRole","resizer").data("layoutEdge",c).css(k.resizers.cssReq).css("zIndex",k.zIndex.resizer_normal).css(e.applyDemoStyles?k.resizers.cssDemo:{}).addClass(h+" "+h+f).appendTo(B);if(o){o.attr("id",e.paneSelector.substr(0,1)=="#"?e.paneSelector.substr(1)+"-toggler":"").data("layoutRole",
"toggler").data("layoutEdge",c).css(k.togglers.cssReq).css(e.applyDemoStyles?k.togglers.cssDemo:{}).addClass(g+" "+g+f).appendTo(j).click(function(m){la(c);m.stopPropagation()}).hover(pa,V);e.togglerContent_open&&i("<span>"+e.togglerContent_open+"</span>").data("layoutRole","togglerContent").data("layoutEdge",c).addClass("content content-open").css("display","none").appendTo(o).hover(pa,V);e.togglerContent_closed&&i("<span>"+e.togglerContent_closed+"</span>").data("layoutRole","togglerContent").data("layoutEdge",
c).addClass("content content-closed").css("display","none").appendTo(o).hover(pa,V)}gb(c);if(d.isVisible)Ga(c);else{Ha(c);qa(c,true)}}});ra("all")},Xa=function(a,b){var c=n[a],e=c.contentSelector,d=q[a],h;if(e)h=ca[a]=c.findNestedContent?d.find(e).eq(0):d.children(e).eq(0);if(h&&h.length){h.css(k.content.cssReq);if(c.applyDemoStyles){h.css(k.content.cssDemo);d.css(k.content.cssDemoPane)}l[a].content={};b!==false&&ma(a)}else ca[a]=false},hb=function(){var a;i.each("toggle,open,close,pin,toggle-slide,open-slide".split(","),
function(b,c){i.each(k.borderPanes.split(","),function(e,d){i(".ui-layout-button-"+c+"-"+d).each(function(){a=i(this).data("layoutName")||i(this).attr("layoutName");if(a==undefined||a==n.name)X(this,c,d)})})})},gb=function(a){var b=typeof i.fn.draggable=="function",c;if(!a||a=="all")a=k.borderPanes;i.each(a.split(","),function(e,d){var h=n[d],g=l[d],f=k[d],j=f.dir=="horz"?"top":"left",o,m;if(!b||!q[d]||!h.resizable){h.resizable=false;return true}var t=A[d],s=h.resizerClass,u=s+"-drag",J=s+"-"+d+"-drag",
R=s+"-dragging",L=s+"-"+d+"-dragging",fa=s+"-dragging-limit",xa=false;g.isClosed||t.attr("title",h.resizerTip).css("cursor",h.resizerCursor);t.hover(bb,Ta);t.draggable({containment:B[0],axis:f.dir=="horz"?"y":"x",delay:0,distance:1,helper:"clone",opacity:h.resizerDragOpacity,addClasses:false,zIndex:k.zIndex.resizer_drag,start:function(){h=n[d];g=l[d];m=h.resizeWhileDragging;if(false===x(d,h.ondrag_start))return false;k.isLayoutBusy=true;g.isResizing=true;D.clear(d+"_closeSlider");U(d);o=g.resizerPosition;
t.addClass(u+" "+J);xa=false;c=i(h.maskIframesOnResize===true?"iframe":h.maskIframesOnResize).filter(":visible");var K,F=0;c.each(function(){K="ui-layout-mask-"+ ++F;i(this).data("layoutMaskID",K);i('<div id="'+K+'" class="ui-layout-mask ui-layout-mask-'+d+'"/>').css({background:"#fff",opacity:"0.001",zIndex:k.zIndex.iframe_mask,position:"absolute",width:this.offsetWidth+"px",height:this.offsetHeight+"px"}).css(i(this).position()).appendTo(this.parentNode)});i("body").disableSelection()},drag:function(K,
F){if(!xa){F.helper.addClass(R+" "+L).children().css("visibility","hidden");xa=true;g.isSliding&&q[d].css("zIndex",k.zIndex.pane_sliding)}var S=0;if(F.position[j]<o.min){F.position[j]=o.min;S=-1}else if(F.position[j]>o.max){F.position[j]=o.max;S=1}if(S){F.helper.addClass(fa);window.defaultStatus="Panel has reached its "+(S>0&&d.match(/north|west/)||S<0&&d.match(/south|east/)?"maximum":"minimum")+" size"}else{F.helper.removeClass(fa);window.defaultStatus=""}m&&W(K,F,d)},stop:function(K,F){i("body").enableSelection();
window.defaultStatus="";t.removeClass(u+" "+J+" "+fa);g.isResizing=false;k.isLayoutBusy=false;W(K,F,d,true)}});var W=function(K,F,S,ib){K=F.position;F=k[S];var sa;switch(S){case "north":sa=K.top;break;case "west":sa=K.left;break;case "south":sa=r.offsetHeight-K.top-h.spacing_open;break;case "east":sa=r.offsetWidth-K.left-h.spacing_open}if(ib){i("div.ui-layout-mask").each(function(){this.parentNode.removeChild(this)});if(false===x(S,h.ondrag_end||h.ondrag))return false}else c.each(function(){i("#"+
i(this).data("layoutMaskID")).css(i(this).position()).css({width:this.offsetWidth+"px",height:this.offsetHeight+"px"})});Ia(S,sa-r["inset"+F.side])}})},Fa=function(a,b){var c=n[a],e=l[a],d=q[a],h=A[a];if(!(!d||e.isHidden))if(!(l.initialized&&false===x(a,c.onhide_start))){e.isSliding=false;h&&h.hide();if(!l.initialized||e.isClosed){e.isClosed=true;e.isHidden=true;e.isVisible=false;d.hide();da(k[a].dir=="horz"?"all":"center");if(l.initialized||c.triggerEventsOnLoad)x(a,c.onhide_end||c.onhide)}else{e.isHiding=
true;Q(a,false,b)}}},ya=function(a,b,c,e){var d=l[a];if(q[a]&&d.isHidden)if(false!==x(a,n[a].onshow_start)){d.isSliding=false;d.isShowing=true;b===false?Q(a,true):aa(a,false,c,e)}},la=function(a,b){if(!M(a)){a.stopImmediatePropagation();a=i(this).data("layoutEdge")}var c=l[M(a)?i.trim(a):a==undefined||a==null?"":a];if(c.isHidden)ya(a);else c.isClosed?aa(a,!!b):Q(a)},jb=function(a){var b=l[a];q[a].hide();b.isClosed=true;b.isVisible=false},Q=function(a,b,c,e){function d(){if(f.isClosed){qa(a,true);
var m=k.altSide[a];if(l[m].noRoom){U(m);ea(m)}if(!e&&(l.initialized||g.triggerEventsOnLoad)){j||x(a,g.onclose_end||g.onclose);if(j)x(a,g.onshow_end||g.onshow);if(o)x(a,g.onhide_end||g.onhide)}}Pa(a)}if(l.initialized){var h=q[a],g=n[a],f=l[a];c=!c&&!f.isClosed&&g.fxName_close!="none";var j=f.isShowing,o=f.isHiding;delete f.isShowing;delete f.isHiding;if(h&&g.closable)if(!(!b&&f.isClosed&&!j))if(k.isLayoutBusy)Oa("close",a,b);else if(!(!j&&false===x(a,g.onclose_start))){k[a].isMoving=true;k.isLayoutBusy=
true;f.isClosed=true;f.isVisible=false;if(o)f.isHidden=true;else if(j)f.isHidden=false;f.isSliding?ta(a,false):da(k[a].dir=="horz"?"all":"center",false);Ha(a);if(c){za(a,true);h.hide(g.fxName_close,g.fxSettings_close,g.fxSpeed_close,function(){za(a,false);d()})}else{h.hide();d()}}}else jb(a)},Ha=function(a){var b=A[a],c=I[a],e=n[a],d=k[a].side.toLowerCase(),h=e.resizerClass,g=e.togglerClass,f="-"+a;b.css(d,r["inset"+k[a].side]).removeClass(h+"-open "+h+f+"-open").removeClass(h+"-sliding "+h+f+"-sliding").addClass(h+
"-closed "+h+f+"-closed").unbind("dblclick."+E);e.resizable&&typeof i.fn.draggable=="function"&&b.draggable("disable").removeClass("ui-state-disabled").css("cursor","default").attr("title","");if(c){c.removeClass(g+"-open "+g+f+"-open").addClass(g+"-closed "+g+f+"-closed").attr("title",e.togglerTip_closed);c.children(".content-open").hide();c.children(".content-closed").css("display","block")}Z(a,false);l.initialized&&ra("all")},aa=function(a,b,c,e){function d(){if(f.isVisible){Sa(a);f.isSliding||
da(k[a].dir=="vert"?"center":"all",false);Ga(a)}Pa(a)}var h=q[a],g=n[a],f=l[a];c=!c&&f.isClosed&&g.fxName_open!="none";var j=f.isShowing;delete f.isShowing;if(!(!h||!g.resizable&&!g.closable))if(!(f.isVisible&&!f.isSliding))if(f.isHidden&&!j)ya(a,true);else if(k.isLayoutBusy)Oa("open",a,b);else if(false!==x(a,g.onopen_start)){U(a,b);if(f.minSize>f.maxSize){Z(a,false);!e&&g.noRoomToOpenTip&&alert(g.noRoomToOpenTip)}else{k[a].isMoving=true;k.isLayoutBusy=true;if(b)ta(a,true);else if(f.isSliding)ta(a,
false);else g.slidable&&qa(a,false);f.noRoom=false;ea(a);f.isVisible=true;f.isClosed=false;if(j)f.isHidden=false;if(c){za(a,true);h.show(g.fxName_open,g.fxSettings_open,g.fxSpeed_open,function(){za(a,false);d()})}else{h.show();d()}}}},Ga=function(a,b){var c=q[a],e=A[a],d=I[a],h=n[a],g=l[a],f=k[a].side.toLowerCase(),j=h.resizerClass,o=h.togglerClass,m="-"+a;e.css(f,r["inset"+k[a].side]+T(a)).removeClass(j+"-closed "+j+m+"-closed").addClass(j+"-open "+j+m+"-open");g.isSliding?e.addClass(j+"-sliding "+
j+m+"-sliding"):e.removeClass(j+"-sliding "+j+m+"-sliding");h.resizerDblClickToggle&&e.bind("dblclick",la);V(0,e);if(h.resizable&&typeof i.fn.draggable=="function")e.draggable("enable").css("cursor",h.resizerCursor).attr("title",h.resizerTip);else g.isSliding||e.css("cursor","default");if(d){d.removeClass(o+"-closed "+o+m+"-closed").addClass(o+"-open "+o+m+"-open").attr("title",h.togglerTip_open);V(0,d);d.children(".content-closed").hide();d.children(".content-open").css("display","block")}Z(a,!g.isSliding);
i.extend(g,ia(c));if(l.initialized){ra("all");ma(a,true)}if(!b&&(l.initialized||h.triggerEventsOnLoad)&&c.is(":visible")){x(a,h.onopen_end||h.onopen);if(g.isShowing)x(a,h.onshow_end||h.onshow);if(l.initialized){x(a,h.onresize_end||h.onresize);ua(a)}}},Za=function(a){var b=typeof a,c=b=="string"?a:i(this).data("layoutEdge");b=="object"&&a.stopImmediatePropagation();l[c].isClosed?aa(c,true):ta(c,true)},Ja=function(a){function b(){e.isClosed?ta(c,false):Q(c)}var c=(M(a)?q[a]:i(this)).data("layoutEdge");
a=n[c];var e=l[c];if(!(e.isClosed||e.isResizing))if(a.slideTrigger_close=="click")b();else a.preventQuickSlideClose&&k.isLayoutBusy||D.set(c+"_closeSlider",b,300)},za=function(a,b){var c=q[a];if(b){c.css({zIndex:k.zIndex.pane_animate});if(a=="south")c.css({top:r.insetTop+r.innerHeight-c.outerHeight()});else a=="east"&&c.css({left:r.insetLeft+r.innerWidth-c.outerWidth()})}else{c.css({zIndex:l[a].isSliding?k.zIndex.pane_sliding:k.zIndex.pane_normal});if(a=="south")c.css({top:"auto"});else a=="east"&&
c.css({left:"auto"});var e=n[a];l.browser.msie&&e.fxOpacityFix&&e.fxName_open!="slide"&&c.css("filter")&&c.css("opacity")==1&&c[0].style.removeAttribute("filter")}},qa=function(a,b){var c=n[a],e=A[a],d=c.slideTrigger_open;if(e&&c.slidable){if(d.match(/mouseover/))d=c.slideTrigger_open="mouseenter";else if(!d.match(/click|dblclick|mouseenter/))d=c.slideTrigger_open="click";e[b?"bind":"unbind"](d+"."+E,Za).css("cursor",b?c.sliderCursor:"default").attr("title",b?c.sliderTip:"")}},ta=function(a,b){function c(o){D.clear(a+
"_closeSlider");o.stopPropagation()}var e=n[a],d=k.zIndex,h=e.slideTrigger_close,g=b?"bind":"unbind",f=q[a],j=A[a];l[a].isSliding=b;D.clear(a+"_closeSlider");b&&qa(a,false);f.css("zIndex",b?d.pane_sliding:d.pane_normal);j.css("zIndex",b?d.pane_sliding:d.resizer_normal);if(!h.match(/click|mouseleave/))h=e.slideTrigger_close="mouseleave";j[g](h,Ja);if(h=="mouseleave"){f[g]("mouseleave."+E,Ja);j[g]("mouseenter."+E,c);f[g]("mouseenter."+E,c)}if(b){if(h=="click"&&!e.resizable){j.css("cursor",b?e.sliderCursor:
"default");j.attr("title",b?e.togglerTip_open:"")}}else D.clear(a+"_closeSlider")},ea=function(a,b,c,e){b=n[a];var d=l[a],h=k[a],g=q[a],f=A[a],j=h.dir=="vert",o=false;if(a=="center"||j&&d.noVerticalRoom)if((o=d.minHeight<=d.maxHeight&&(j||d.minWidth<=d.maxWidth))&&d.noRoom){g.show();f&&f.show();d.isVisible=true;d.noRoom=false;if(j)d.noVerticalRoom=false;Sa(a)}else if(!o&&!d.noRoom){g.hide();f&&f.hide();d.isVisible=false;d.noRoom=true}if(a!="center")if(d.minSize<=d.maxSize){if(d.size>d.maxSize)na(a,
d.maxSize,c,e);else if(d.size<d.minSize)na(a,d.minSize,c,e);else if(f&&g.is(":visible")){c=h.side.toLowerCase();e=d.size+r["inset"+h.side];ha(f,c)!=e&&f.css(c,e)}if(d.noRoom)if(d.wasOpen&&b.closable)if(b.autoReopen)aa(a,false,true,true);else d.noRoom=false;else ya(a,d.wasOpen,true,true)}else if(!d.noRoom){d.noRoom=true;d.wasOpen=!d.isClosed&&!d.isSliding;b.closable?Q(a,true,true):Fa(a,true)}},Ia=function(a,b,c){var e=n[a],d=e.resizeWhileDragging&&!k.isLayoutBusy;e.autoResize=false;na(a,b,c,d)},na=
function(a,b,c,e){var d=n[a],h=l[a],g=q[a],f=A[a],j=k[a].side.toLowerCase(),o="inset"+k[a].side,m=k.isLayoutBusy&&!d.triggerEventsWhileDragging,t;U(a);t=h.size;b=ba(a,b);b=z(b,ba(a,d.minSize));b=Math.min(b,h.maxSize);if(b<h.minSize)ea(a,false,c);else if(!(!e&&b==t)){!c&&l.initialized&&h.isVisible&&x(a,d.onresize_start);g.css(k[a].sizeType.toLowerCase(),z(1,k[a].dir=="horz"?O(a,b):N(a,b)));h.size=b;i.extend(h,ia(g));f&&g.is(":visible")&&f.css(j,b+r[o]);ma(a);if(!c&&!m&&l.initialized&&h.isVisible){x(a,
d.onresize_end||d.onresize);ua(a)}if(!c){h.isSliding||da(k[a].dir=="horz"?"all":"center",m,e);ra("all")}a=k.altSide[a];if(b<t&&l[a].noRoom){U(a);ea(a,false,c)}}},da=function(a,b,c){if(!a||a=="all")a="east,west,center";i.each(a.split(","),function(e,d){if(q[d]){var h=n[d],g=l[d],f=q[d],j=true,o={};j={top:T("north",true),bottom:T("south",true),left:T("west",true),right:T("east",true),width:0,height:0};j.width=r.innerWidth-j.left-j.right;j.height=r.innerHeight-j.bottom-j.top;j.top+=r.insetTop;j.bottom+=
r.insetBottom;j.left+=r.insetLeft;j.right+=r.insetRight;i.extend(g,ia(f));if(d=="center"){if(!c&&g.isVisible&&j.width==g.outerWidth&&j.height==g.outerHeight)return true;i.extend(g,va(d),{maxWidth:j.width,maxHeight:j.height});o=j;o.width=N(d,j.width);o.height=O(d,j.height);j=o.width>0&&o.height>0;if(!j&&!l.initialized&&h.minWidth>0){var m=h.minWidth-g.outerWidth,t=n.east.minSize||0,s=n.west.minSize||0,u=l.east.size,J=l.west.size,R=u,L=J;if(m>0&&l.east.isVisible&&u>t){R=z(u-t,u-m);m-=u-R}if(m>0&&l.west.isVisible&&
J>s){L=z(J-s,J-m);m-=J-L}if(m==0){u!=t&&na("east",R,true);J!=s&&na("west",L,true);da("center",b,c);return}}}else{i.extend(g,ia(f),va(d));if(!c&&!g.noVerticalRoom&&j.height==g.outerHeight)return true;o.top=j.top;o.bottom=j.bottom;o.height=O(d,j.height);g.maxHeight=z(0,o.height);j=g.maxHeight>0;if(!j)g.noVerticalRoom=true}if(j){!b&&l.initialized&&x(d,h.onresize_start);f.css(o);i.extend(g,ia(f));g.noRoom&&ea(d);l.initialized&&ma(d)}else!g.noRoom&&g.isVisible&&ea(d);if(d=="center"){f=l.browser;f=f.isIE6||
f.msie&&!f.boxModel;if(q.north&&(f||l.north.tagName=="IFRAME"))q.north.css("width",N(q.north,r.innerWidth));if(q.south&&(f||l.south.tagName=="IFRAME"))q.south.css("width",N(q.south,r.innerWidth))}if(!b&&l.initialized&&g.isVisible){x(d,h.onresize_end||h.onresize);ua(d)}}})},wa=function(){i.extend(l.container,ia(B));if(r.outerHeight){if(false===x(null,n.onresizeall_start))return false;var a,b,c;i.each(["south","north","east","west"],function(e,d){if(q[d]){c=l[d];b=n[d];if(b.autoResize&&c.size!=b.size)na(d,
b.size,true,true);else{U(d);ea(d,false,true,true)}}});da("all",true,true);ra("all");b=n;i.each(k.allPanes.split(","),function(e,d){if(a=q[d]){if(l[d].isVisible)x(d,b[d].onresize_end||b[d].onresize);ua(d)}});x(null,b.onresizeall_end||b.onresizeall)}},ua=function(a){var b=q[a],c=ca[a];if(n[a].resizeNestedLayout)if(b.data("layoutContainer"))b.layout().resizeAll();else c&&c.data("layoutContainer")&&c.layout().resizeAll()},ma=function(a,b){if(!a||a=="all")a=k.allPanes;i.each(a.split(","),function(c,e){function d(t){return z(o.css.paddingBottom,
parseInt(t.css("marginBottom"),10)||0)}function h(){var t=n[e].contentIgnoreSelector;t=f.nextAll().not(t||":lt(0)");var s=t.filter(":visible"),u=s.filter(":last");m={top:f[0].offsetTop,height:f.outerHeight(),numFooters:t.length,hiddenFooters:t.length-s.length,spaceBelow:0};m.spaceAbove=m.top;m.bottom=m.top+m.height;m.spaceBelow=u.length?u[0].offsetTop+u.outerHeight()-m.bottom+d(u):d(f)}var g=q[e],f=ca[e],j=n[e],o=l[e],m=o.content;if(!g||!f||!g.is(":visible"))return true;if(false!==x(null,j.onsizecontent_start)){if(!k.isLayoutBusy||
m.top==undefined||b||j.resizeContentWhileDragging){h();if(m.hiddenFooters>0&&g.css("overflow")=="hidden"){g.css("overflow","visible");h();g.css("overflow","hidden")}}g=o.innerHeight-(m.spaceAbove-o.css.paddingTop)-(m.spaceBelow-o.css.paddingBottom);if(!f.is(":visible")||m.height!=g){ab(f,g,true);m.height=g}if(l.initialized){x(e,j.onsizecontent_end||j.onsizecontent);ua(e)}}})},ra=function(a){if(!a||a=="all")a=k.borderPanes;i.each(a.split(","),function(b,c){var e=n[c],d=l[c],h=q[c],g=A[c],f=I[c],j;
if(h&&g){var o=k[c].dir,m=d.isClosed?"_closed":"_open",t=e["spacing"+m],s=e["togglerAlign"+m];m=e["togglerLength"+m];var u;if(t==0)g.hide();else{!d.noRoom&&!d.isHidden&&g.show();if(o=="horz"){u=h.outerWidth();d.resizerLength=u;g.css({width:z(1,N(g,u)),height:z(0,O(g,t)),left:ha(h,"left")})}else{u=h.outerHeight();d.resizerLength=u;g.css({height:z(1,O(g,u)),width:z(0,N(g,t)),top:r.insetTop+T("north",true)})}V(e,g);if(f){if(m==0||d.isSliding&&e.hideTogglerOnSlide){f.hide();return}else f.show();if(!(m>
0)||m=="100%"||m>u){m=u;s=0}else if(M(s))switch(s){case "top":case "left":s=0;break;case "bottom":case "right":s=u-m;break;default:s=Math.floor((u-m)/2)}else{d=parseInt(s,10);s=s>=0?d:u-m+d}if(o=="horz"){var J=N(f,m);f.css({width:z(0,J),height:z(1,O(f,t)),left:s,top:0});f.children(".content").each(function(){j=i(this);j.css("marginLeft",Math.floor((J-j.outerWidth())/2))})}else{var R=O(f,m);f.css({height:z(0,R),width:z(1,N(f,t)),top:s,left:0});f.children(".content").each(function(){j=i(this);j.css("marginTop",
Math.floor((R-j.outerHeight())/2))})}V(0,f)}if(!l.initialized&&e.initHidden){g.hide();f&&f.hide()}}}})},B=i(this).eq(0);if(!B.length)return null;if(B.data("layoutContainer"))return i.extend({},window[B.data("layoutContainer")]);var q={},ca={},A={},I={},r=l.container,E=l.id;(function(){eb();var a=n;if(false===x(null,a.onload))return false;if(!Wa("center").length){alert(C.errCenterPaneMissing);return null}a.useStateCookie&&a.cookie.autoLoad&&Ma();l.browser={mozilla:i.browser.mozilla,webkit:i.browser.webkit||
i.browser.safari,msie:i.browser.msie,isIE6:i.browser.msie&&i.browser.version==6,boxModel:i.support.boxModel};var b=B,c=r.tagName=b.attr("tagName"),e=c=="BODY",d={};r.selector=b.selector.split(".slice")[0];r.ref=c+"/"+r.selector;b.data("layoutContainer",E).data("layoutName",n.name);if(!b.data("layoutCSS")){if(e){d=i.extend(Da(b,"position,margin,padding,border"),{height:b.css("height"),overflow:b.css("overflow"),overflowX:b.css("overflowX"),overflowY:b.css("overflowY")});c=i("html");c.data("layoutCSS",
{height:"auto",overflow:c.css("overflow"),overflowX:c.css("overflowX"),overflowY:c.css("overflowY")})}else d=Da(b,"position,margin,padding,border,top,bottom,left,right,width,height,overflow,overflowX,overflowY");b.data("layoutCSS",d)}try{if(e){i("html").css({height:"100%",overflow:"hidden",overflowX:"hidden",overflowY:"hidden"});i("body").css({position:"relative",height:"100%",overflow:"hidden",overflowX:"hidden",overflowY:"hidden",margin:0,padding:0,border:"none"})}else{d={overflow:"hidden"};var h=
b.css("position");b.css("height");if(!b.data("layoutRole"))if(!h||!h.match(/fixed|absolute|relative/))d.position="relative";b.css(d);b.is(":visible")&&b.innerHeight()<2&&alert(C.errContainerHeight.replace(/CONTAINER/,r.ref))}}catch(g){}i.extend(l.container,ia(b));fb();ma();if(a.scrollToBookmarkOnLoad){b=self.location;b.hash&&b.replace(b.hash)}a.autoBindCustomButtons&&hb();db();a.resizeWithWindow&&!B.data("layoutRole")&&i(window).bind("resize."+E,cb);i(window).bind("unload."+E,Va);l.initialized=true})();
var Qa={options:n,state:l,container:B,panes:q,contents:ca,resizers:A,togglers:I,toggle:la,hide:Fa,show:ya,open:aa,close:Q,slideOpen:Za,slideClose:Ja,slideToggle:function(a){la(a,true)},initContent:Xa,sizeContent:ma,sizePane:Ia,swapPanes:function(a,b){function c(f){var j=q[f],o=ca[f];return!j?false:{pane:f,P:j?j[0]:false,C:o?o[0]:false,state:i.extend({},l[f]),options:i.extend({},n[f])}}function e(f,j){if(f){var o=f.P,m=f.C,t=f.pane,s=k[j],u=s.side.toLowerCase(),J="inset"+s.side,R=i.extend({},l[j]),
L=n[j],fa={resizerCursor:L.resizerCursor};i.each("fxName,fxSpeed,fxSettings".split(","),function(xa,W){fa[W]=L[W];fa[W+"_open"]=L[W+"_open"];fa[W+"_close"]=L[W+"_close"]});q[j]=i(o).data("layoutEdge",j).css(k.hidden).css(s.cssReq);ca[j]=m?i(m):false;n[j]=i.extend({},f.options,fa);l[j]=i.extend({},f.state);o.className=o.className.replace(RegExp(L.paneClass+"-"+t,"g"),L.paneClass+"-"+j);Ya(j);if(s.dir!=k[t].dir){o=g[j]||0;U(j);o=z(o,l[j].minSize);Ia(j,o,true)}else A[j].css(u,r[J]+(l[j].isVisible?T(j):
0));if(f.state.isVisible&&!R.isVisible)Ga(j,true);else{Ha(j);qa(j,true)}f=null}}l[a].edge=b;l[b].edge=a;var d=false;if(false===x(a,n[a].onswap_start))d=true;if(!d&&false===x(b,n[b].onswap_start))d=true;if(d){l[a].edge=a;l[b].edge=b}else{d=c(a);var h=c(b),g={};g[a]=d?d.state.size:0;g[b]=h?h.state.size:0;q[a]=false;q[b]=false;l[a]={};l[b]={};I[a]&&I[a].remove();I[b]&&I[b].remove();A[a]&&A[a].remove();A[b]&&A[b].remove();A[a]=A[b]=I[a]=I[b]=false;e(d,b);e(h,a);d=h=g=null;q[a]&&q[a].css(k.visible);q[b]&&
q[b].css(k.visible);wa();x(a,n[a].onswap_end||n[a].onswap);x(b,n[b].onswap_end||n[b].onswap)}},resizeAll:wa,destroy:function(){i(window).unbind("."+E);i(document).unbind("."+E);window[E]=null;var a=r.tagName=="BODY",b,c,e,d;i.each(k.allPanes.split(","),function(h,g){b=q[g];if(!b)return true;if(g!="center"){I[g]&&I[g].remove();A[g].remove()}c=n[g].paneClass;e=c+"-"+g;d=[c,c+"-open",c+"-closed",c+"-sliding",e,e+"-open",e+"-closed",e+"-sliding"];i.merge(d,Ea(b,true));b.removeClass(d.join(" ")).removeData("layoutRole").removeData("layoutEdge").unbind("."+
E).unbind("mouseenter").unbind("mouseleave");b.data("layoutContainer")||b.css(b.data("layoutCSS"))});B.removeData("layoutContainer");B.data("layoutEdge")||B.css(B.data("layoutCSS"));a&&i("html").css(i("html").data("layoutCSS"));Va();if((a=n.name)&&window[a])window[a]=null},setSizeLimits:U,bindButton:X,addToggleBtn:Y,addOpenBtn:H,addCloseBtn:G,addPinBtn:ka,allowOverflow:w,resetOverflow:y,encodeJSON:La,decodeJSON:Ka,getState:Ba,getCookie:ga,saveCookie:Aa,deleteCookie:function(){Aa("",{expires:-1})},
loadCookie:Ma,loadState:Na,cssWidth:N,cssHeight:O};return window[E]=Qa}})(jQuery);
